### ISSUE TITLE
CLO APIs and documentation

### ISSUE THREAD

**Issue by ricardobrg** [tiki/apps#27]
### Description

Define the APIs that will be used for CLO Cashback Connections features in Android and iOS Rewards SDKs, considering the information that needs to be exchanged with our backend services and Kard API, and add its respective documentation.

### Issues

- [x] tiki/apps-rewards-ios#55
- [x] tiki/apps-rewards-android#75
- [ ] tiki/apps#32

**Comment by mike-audi** [comment]
blocked waiting on @mike-audi to review final issue.
