### ISSUE TITLE
Compile API Documentation

### ISSUE THREAD

**Issue by sfaria27** [tiki/apps#61]
As a team member, I need to compile documentation on the APIs involved in the receipt scanning feature for the high-level system overview. This documentation will provide a comprehensive understanding of the external interfaces and integrations.

## Acceptance Criteria
- Identify all APIs integrated into the receipt scanning feature.
- Document the purpose and functionalities of each API.
- Specify the communication protocols and data formats used by the APIs.
- Ensure the documentation is organized and easily accessible.
- Include any authentication mechanisms or security considerations associated with the APIs.

**Comment by ricardobrg** [comment]
A draft fot this documentation is in https://github.com/tiki/apps/issues/60. After we decide in the deliverables I will improve the technical docs as needed.
